SELECT * FROM DEPOSITE
WHERE BNAME!='ANDHERI'

SELECT CNAME FROM BORROW 
WHERE AMOUNT IS NULL

SELECT ACTNO, CNAME, AMOUNT FROM DEPOSITE 
WHERE BNAME='AJNI' OR BNAME='KAROLBAGH' OR BNAME='M.G. ROAD'
AND ACTNO<104

SELECT TOP 5 * FROM DEPOSITE

SELECT TOP 3 * FROM DEPOSITE
WHERE AMOUNT>1000

SELECT TOP 5 LOANNO, CNAME FROM BORROW
WHERE BNAME <> 'ANDHERI'

SELECT DISTINCT CITY FROM CUSTOMERS

SELECT DISTINCT BNAME FROM BRANCH

SELECT * FROM CUSTOMERS
ORDER BY CITY

SELECT * FROM DEPOSITE
ORDER BY AMOUNT DESC

SELECT * FROM CUSTOMERS
ORDER BY CITY DESC

SELECT DISTINCT CNAME AS UNI_BORROWERS FROM BORROW

