CREATE DATABASE BANK_INFO

CREATE TABLE DEPOSITE
(
	ACTNO int,
	CNAME varchar(50),
	BNAME varchar(50),
	AMOUNT Decimal(8,2),
	ADATE datetime
)

CREATE TABLE BRANCH
(
	BNAME varchar(50),
	CITY varchar(50)
)

CREATE TABLE CUSTOMERS
(
	CNAME varchar(50),
	CITY varchar(50)
)

CREATE TABLE BORROW
(
	LOANNO int,
	CNAME varchar(50),
	BNAME varchar(50),
	AMOUNT decimal(8,2)
)

INSERT INTO DEPOSITE
VALUES (104, 'MADHURI', 'CHANDNI', 1200.00, '12-17-95'),
		(105, 'PRAMOD', 'M.G.ROAD', 3000.00, '3-27-96'),
		(106, 'SANDIP', 'ANDHERI', 2000.00, '3-31-96'),
		(107, 'SIVANI', 'VIRAR', 1000.00, '9-5-95'),
		(108, 'KRANTI', 'NEHRU PLACE', 5000.00, '7-2-95'),
		(109, 'MINU', 'POWAL', 7000.00, '8-10-95')

SELECT * FROM DEPOSITE

INSERT INTO BRANCH
VALUES ('VRCE', 'NAGPUR'),
		('AJNI', 'NAGPUR'),
		('KAROLBHAG', 'DILHI'),
		('CHANDNI', 'DILHI'),
		('DHARAMPRTH', 'NAGPUR'),
		('M.G.ROAD', 'BANGLORE'),
		('ANDHERY', 'BOMBAY'),
		('VIHAR', 'BOMBAY'),
		('NEHRU PLACE', 'DILHI'),
		('POWAI', 'BOMBAY')

SELECT * FROM BRANCH

INSERT INTO CUSTOMERS
VALUES ('ANIL', 'CALCUTTA'),
		('SUNIL', 'DELHI'),
		('MEHUL', 'BARODA'),
		('MANDAR', 'PATNA'),
		('MADHURI', 'NAGPUR'),
		('PRAMOD', 'NAGPUR'),
		('SANDIP', 'SURAT'),
		('SHIVANI', 'BOMBAY'),
		('KRANTI', 'BOMBAY'),
		('NARENA', 'BOMBAY')

SELECT * FROM CUSTOMERS

INSERT INTO BORROW
VALUES (201, 'ANIL', 'VRCE', 1000.00),
		(206, 'MEHUL', 'AJNI', 5000.00),
		(311, 'SUNIL', 'DHARMPETH', 3000.00),
		(321, 'MADHURI', 'ANDHERI', 2000.00),
		(375, 'PRMOD', 'VIHAR', 8000.00),
		(481, 'KRANTI', 'NEHRU PLACE', 3000.00)

SELECT * FROM BORROW



